spring:
  application:
    name: zipkin-server
  cloud:
    nacos:
      discovery:
        server-addr: 20.50.54.194:8848
    main:
      allow-bean-definition-overriding: true

zipkin:
  collector:
    rabbitmq:
      addresses: 20.50.54.194:5672
      password: admin
      username: admin
      queue: zipkin

server:
  port: 30000


management:
  metrics:
    web:
      server:
        auto-time-requests: false