server:
  port: 21000
  error:
    includeException: true
    includeStacktrace: ON_PARAM
    includeMessage: ALWAYS

spring:
  application:
    name: employee-service
  cloud:
    nacos:
      discovery:
        server-addr: 20.50.54.194:8848
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://20.50.54.71:3306/employee_db?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: qr@f7yNb98bnlKj43wuh
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

restroom-service:
  ribbon:
    # 指定负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: restroom-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有endpoint
        include: '*'
  security:
    enabled: false