server:
  port: 21000
  error:
    includeException: true
    includeStacktrace: ON_PARAM
    includeMessage: ALWAYS

spring:
  application:
    name: employee-service
  sleuth:
    sampler:
      #采样率 100%
      probability: 1
      # 每秒最多采样100个trace
      rate: 100
  zipkin:
    sender:
      type: web
    discovery-client-enabled: true
    base-url: http://zipkin-server
    locator:
      discovery:
        enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 20.50.54.194:8848
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://20.50.54.71:3306/employee_db?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: qr@f7yNb98bnlKj43wuh
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1

restroom-service:
  ribbon:
    # 指定负载均衡策略，细粒度配置，会覆盖全局配置
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ConnectTimeout: 1000 # 服务请求的连接超时时间
    ReadTimeout: 2000 # 服务请求处理超时时间
    # 注意 post put delete 确保幂等性
    OkToRetryOnAllOperations: false # 是否对所有请求启动重试机制
    MaxAutoRetries: 1 #每个实例重试次数
    MaxAutoRetriesNextServer: 1 # 切换几个实例进行测试

# 饥饿加载,全局配置
ribbon:
  eager-load:
    enabled: true
    clients: restroom-service
  ConnectTimeout: 1000 # 服务请求的连接超时时间
  ReadTimeout: 1000 # 服务请求处理超时时间
  # 注意 post put delete 确保幂等性
  OkToRetryOnAllOperations: false # 是否对所有请求启动重试机制
  MaxAutoRetries: 2 #每个实例重试次数
  MaxAutoRetriesNextServer: 2 # 切换几个实例进行测试

feign:
  compression:
    request:
      enabled: false
      min-request-size: 4096
    response:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有endpoint
        include: '*'
  security:
    enabled: false

logging:
  level:
    ROOT: info
    com.ryan.employee.feign.RestroomFeignClient: debug
  pattern:
    dateformat: HH:mm:ss.SSS
