server:
  port: 20000
  compression:
    enabled: true
  error:
    includeException: true
    includeStacktrace: ON_PARAM
    includeMessage: ALWAYS

spring:
  application:
    name: restroom-service
  sleuth:
    sampler:
      #采样率 100%
      probability: 1
      # 每秒最多采样100个trace
      rate: 100
  zipkin:
    sender:
      type: web
    discovery-client-enabled: true
    base-url: http://zipkin-server
    locator:
      discovery:
        enabled: true

  cloud:
    nacos:
      discovery:
        server-addr: 20.50.54.194:8848
        metadata:
          myname: ryan
          mylover: wy
        # 起别名，代替application name
#        service: restroom-service
        # 心跳间隔时间
        heart-beat-interval: 5000
        # 服务器踢出的事件（标记不健康），默认15s,如果想服务器尽快踢出不健康的实例，时间可以设置短些
        heart-beat-timeout: 15000
        # 防止意外宕机的防范措施
#        naming-load-cache-at-start: false
#        cluster-name: Cluster-2
#        namespace: a6eb9a92-9092-41ea-8902-c9907a7103cc
#        group: myGroup
#        # 是否向nacos发起服务注册,服务发现功能还在
#        register-enabled: false
#        # 监听服务端的信息变化
#        watch:
#          enabled: true
#        watch-delay: 30000



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://20.50.54.71:3306/toilet_db?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: qr@f7yNb98bnlKj43wuh
    type: com.zaxxer.hikari.HikariDataSource            # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver         # mysql驱动
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 暴露所有endpoint
        include: '*'
  security:
    enabled: false